message("Configuring files")

set(ROOT_DIRECTORY ${CMAKE_CURRENT_LIST_DIR})
set(ASSET_DIRECTORY ${ROOT_DIRECTORY}/assets)

file(GLOB_RECURSE CLIENT_FILES "${ASSET_DIRECTORY}/*")

foreach (CLIENT_FILE ${CLIENT_FILES})
    file(RELATIVE_PATH REL_PATH ${ASSET_DIRECTORY} ${CLIENT_FILE})
    configure_file(${CLIENT_FILE} ${REL_PATH} COPYONLY)
endforeach (${CLIENT_FILE})